{application,expty,
             [{modules,['Elixir.ExPTY','Elixir.ExPTY.Application',
                        'Elixir.ExPTY.Nif','Elixir.ExPTY.SmartCell']},
              {optional_applications,[kino]},
              {applications,[kernel,stdlib,elixir,cc_precompiler,elixir_make,
                             kino]},
              {description,"`forkpty(3)` bindings for elixir"},
              {registered,[]},
              {vsn,"0.2.1"},
              {mod,{'Elixir.ExPTY.Application',[]}}]}.
